### ISSUE TITLE
Do it work?

### ISSUE THREAD

**Issue by mrc4tt** [HugoJF/pterodactyl-csgo-fast-install#1]
Hi. @HugoJF 

Do this still work for pterodactyl 0.7 or only the newest version?

I was confused about the README. because I don't see where it will do: ``cp -avrl`` from the daemon. ^^
Right now, the installation takes 5 minutes. about it's possible to "minimal" it lower?

If you have some tip/idea, with doing: "CS:GO master-server directory" for docker e.g

*Sorry for disturbing you*

**Comment by HugoJF** [comment]
> Do this still work for pterodactyl 0.7 or only the newest version?

I haven't touched it since 0.7, so it should still be working fine.

> I was confused about the README. because I don't see where it will do: cp -avrl from the daemon. ^^

I had a modified version of the daemon (not sure if I published it here) that would check for installation files and copy them using hard-links. I used `mergerfs` that would CoW hard-links so instead of relying on SteamCMD, I just linked everything to the new installation. CoW will copy the file once it's modified, that way if one person modifieds `maplist.txt`, this change will not change for other clients.

That way you have file deduplication and extremely fast installations.

> Right now, the installation takes 5 minutes. about it's possible to "minimal" it lower?

I managed to get <35 second installations from clicking "Create server" to full boot. Demo: https://gfycat.com/ablefragrantbeardedcollie

> If you have some tip/idea, with doing: "CS:GO master-server directory" for docker e.g

You need to run a filesystem that supports CoW, host Pterodactyl server files there, modify the Daemon to copy the files to the new installation before running SteamCMD to check it's updated. You also need a cronjob to keep the master-server updated too.

Feel free to ask me any questions about this, I'm closing this issue as it's not a issue with the image itself.

**Comment by mrc4tt** [comment]
Hi @HugoJF sorry for tagging.

Can I contact you about a price deal for setup this on my dev-server? ^^
I can be added on discord: mrc4t#2090 (- I have also sent you an e-mail)
